version: '3'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./postgres-data:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DB_URL: postgresql://admin:admin@metro-tasks-db-1:5432/mydb
    depends_on:
      - db